language: python
cache:
  pip: true
dist: xenial
addons:
  apt:
    update: yes

stages:
- "Unit test"
- "End-to-end test"

python:
- "3.4"
- "3.5"
- "3.6"
env:
- TEST_MODE=e2e-prosody PROSODY_BRANCH=0.11 WITH_BUILD_DEP=yes
stage: "End-to-End Test"
matrix:
  include:
  - python: "3.6"
    stage: "End-to-End Test"
    env: TEST_MODE=e2e-ejabberd EJABBERD_VERSION=latest
    services:
    - docker
  - python: "3.6"
    stage: "End-to-End Test"
    env: TEST_MODE=e2e-ejabberd EJABBERD_VERSION=18.03
    services:
    - docker
  - python: "3.6"
    stage: "End-to-End Test"
    env: TEST_MODE=e2e-ejabberd EJABBERD_VERSION=18.09
    services:
    - docker
  - python: "3.6"
    stage: "End-to-End Test"
    env: TEST_MODE=e2e-prosody PROSODY_BRANCH=0.9 LUA_VERSION=5.1 WITH_BUILD_DEP=yes
  - python: "3.6"
    stage: "End-to-End Test"
    env: TEST_MODE=e2e-prosody PROSODY_BRANCH=0.10 LUA_VERSION=5.1 WITH_BUILD_DEP=yes
  - python: "3.6"
    stage: "End-to-End Test"
    env: TEST_MODE=e2e-prosody PROSODY_BRANCH=trunk WITH_BUILD_DEP=yes
  - python: "3.6"
    stage: "End-to-End Test"
    env: TEST_MODE=e2e-metronome METRONOME_VERSION=master
    addons:
      apt:
        packages:
        - libevent-dev
  - python: "3.6"
    stage: "Unit test"
    env: TEST_MODE=coverage
  - sudo: required
    dist: xenial
    stage: "End-to-End Test"
    python: "3.7"
    addons:
      apt:
        update: yes
    env: TEST_MODE=e2e-prosody PROSODY_BRANCH=0.11 WITH_BUILD_DEP=yes
  allow_failures:
  - python: "3.6"
    stage: "End-to-End Test"
    env: TEST_MODE=e2e-prosody PROSODY_BRANCH=trunk WITH_BUILD_DEP=yes
  - python: "3.6"
    stage: "End-to-End Test"
    env: TEST_MODE=e2e-metronome METRONOME_VERSION=master
    addons:
      apt:
        packages:
        - libevent-dev
  - python: "3.6"
    stage: "End-to-End Test"
    env: TEST_MODE=e2e-ejabberd EJABBERD_VERSION=latest
    services:
    - docker

before_install:
- export PATH=$PWD/lua_install/bin:$PATH
- if [[ "x$TEST_MODE" = 'xe2e-prosody' ]]; then ./utils/install-prosody.sh; fi
- if [[ "x$TEST_MODE" = 'xe2e-metronome' ]]; then ./utils/install-metronome.sh; fi
- if [[ "x$TEST_MODE" = 'xe2e-ejabberd' ]]; then ./utils/prepare-ejabberd.sh; fi
install:
- pip install nose coveralls
- pip install .
script:
- export PATH=$PWD/lua_install/bin:$PATH
- if [[ "x$TEST_MODE" = 'xe2e-prosody' ]]; then ./utils/travis-e2etest-prosody.py; fi
- if [[ "x$TEST_MODE" = 'xe2e-metronome' ]]; then ./utils/travis-e2etest-metronome.py; fi
- if [[ "x$TEST_MODE" = 'xe2e-ejabberd' ]]; then ./utils/travis-e2etest-ejabberd.py; fi
- if [[ "x$TEST_MODE" = 'xcoverage' ]]; then nosetests --with-cover --cover-package aioxmpp tests; fi
after_success:
- if [[ "x$TEST_MODE" = 'xcoverage' ]]; then coveralls; fi
